package com.example.WorkOUT.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private UserRepository userRepository;

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<User> getAllUsers() throws Throwable {
        // This returns a JSON or XML with the users
        try {
            return userRepository.findAll();
        } catch (Exception exception) {
            throw exception.getCause();
        }
    }


    @PostMapping(path = "/add", consumes = "application/json", produces = "application/json") // Map ONLY POST Requests
    public @ResponseBody
    ResponseEntity<User> addNewUser(@RequestBody User user) {
        String username = user.getUsername();
        String password = user.getPassword();
        String gender = user.getGender();
        String email = user.getEmail();

        boolean emailExists = userRepository.existsByEmail(email);
        if (emailExists) {
            user = userRepository.findUserByEmail(email).get(0);
            return new ResponseEntity<>(user, HttpStatus.CONFLICT);
        }

        boolean usernameExists = userRepository.existsByUsername(username);
        if (usernameExists) {
            user = userRepository.findUserByUsername(username).get(0);
            return new ResponseEntity<>(user, HttpStatus.CONFLICT);
        }
        user = new User();
        user.setEmail(email);
        user.setGender(gender);
        user.setPassword(password);
        user.setUsername(username);
        userRepository.save(user);
        return new ResponseEntity<>(user, HttpStatus.OK);
    }


//    @PostMapping(path="/add", consumes="application/json", produces = "application/json") // Map ONLY POST Requests
//    public @ResponseBody String addNewUser (
//            @RequestParam String username, @RequestParam String password, @RequestParam String gender, @RequestParam String email) {
//            User user = new User();
//            user.setUsername(username);
//            user.setEmail(email);
//            user.setPassword(password);
//            user.setGender(gender);
//            userRepository.save(user);
//            return "Saved";
//    }

    @PutMapping(path = "/update")
    public @ResponseBody
    String updateUser(@RequestParam User user) throws Throwable {
        try {
            if (userRepository.existsByUserID(user.getId())) {
                userRepository.save(user);
                return "User " + user.getId() + " has been saved!";
            }
            return "Error: Could not find the user!";
        } catch (Exception exception) {
            throw exception.getCause();
        }
    }

    @DeleteMapping(path = "/delete")
    public @ResponseBody
    String deleteUser(@RequestParam User user) throws Throwable {
        try {
            if (userRepository.existsByUserID(user.getId())) {
                userRepository.delete(user);
                return "User " + user.getId() + " has been removed!";
            }
            return "Error: Could not find the user!";
        } catch (Exception exception) {
            throw exception.getCause();
        }
    }

    @PostMapping(path = "/login", consumes = "application/json", produces = "application/json")
    public @ResponseBody
    ResponseEntity<Boolean> loginUser(@RequestBody User user) {
        if (userRepository.existsByEmailAndPassword(user.getEmail(), user.getPassword())) {
            return new ResponseEntity<>(true, HttpStatus.OK);
        } else {
            return new ResponseEntity<>(false, HttpStatus.OK);
        }
    }

    /*@GetMapping(path = "/usernameinfo", consumes="application/json", produces="application/json")
    public @ResponseBody ResponseEntity<String> getUsernameInfo(@RequestBody User user) {
        if (userRepository.existsByEmail(user.getEmail())){
            return new ResponseEntity<>(user.getUsername(), HttpStatus.OK);
        }
        else {
            return new ResponseEntity<>(null, HttpStatus.OK);
        }
    }*/


    //Rebecca test - med Robert: fungerar
    @GetMapping(path = "/username", produces = "application/json")
    public @ResponseBody
    ResponseEntity<User> getUsernameInfoRebecca(@RequestParam String email) {
        if (userRepository.existsByEmail(email)) {
            return new ResponseEntity<>(userRepository.findUserByEmail(email).get(0), HttpStatus.OK);
        } else {
            return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
        }
    }





    /*@GetMapping(path = "/userName")
    @ResponseBody
    public String getFoos(@RequestParam String id) {
        if (userRepository.existsByEmail(user.getEmail())){
            return new ResponseEntity<>(user.getUsername(), HttpStatus.OK);
        }
        else {
            return new ResponseEntity<>(null, HttpStatus.OK);
        }
    }*/
}